name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: sudo apt install xorriso
    - name: make
      run: make iso
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0
    - name: Upload Kernel
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: Kernel(run using limine)
        # A file, directory or wildcard pattern that describes what to upload
        path: out.kern
    - name: Upload Image
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: iso image(bios and uefi bootable)
        # A file, directory or wildcard pattern that describes what to upload
        path: image.iso
